---
kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

event:
  - push

steps:
  - name: restore_cache
    image: curlimages/curl
    user: root
    environment:
      WEBDAV_CACHE_ADDRESS:
        from_secret: webdav-cache-address
      WEBDAV_CACHE_USERNAME:
        from_secret: webdav-cache-username
      WEBDAV_CACHE_PASSWORD:
        from_secret: webdav-cache-password
    commands:
      - echo .m2 .cache | tr ' ' '\n' | xargs -P5 -i /bin/sh -c 'mkdir -p {} && curl --user "$${WEBDAV_CACHE_USERNAME}:$${WEBDAV_CACHE_PASSWORD}" $${WEBDAV_CACHE_ADDRESS}/${DRONE_REPO_NAME}/${DRONE_BRANCH}/$$(echo {} | tr -d / ) | tar -xC {} || true'

  - name: deploy
    image: maven:3-adoptopenjdk-8
    commands:
      - mkdir -p $${HOME}/.m2
      - echo '<settings><servers><server><id>therepo</id><username>$${repo.user}</username><password>$${repo.pass}</password></server></servers></settings>' > $${HOME}/.m2/settings.xml
      - mvn deploy -DskipTests -DaltDeploymentRepository=therepo::default::$${DEPLOY_REPO} -Drepo.user=$${DEPLOY_USER} -Drepo.pass=$${DEPLOY_PASS} -Drevision=${DRONE_COMMIT_SHA:0:7}
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"
      DEPLOY_REPO:
        from_secret: maven-deploy-repo
      DEPLOY_USER:
        from_secret: maven-deploy-user
      DEPLOY_PASS:
        from_secret: maven-deploy-pass
    when:
      event:
        exclude:
          - pull_request

  - name: build_and_test
    image: maven:3-adoptopenjdk-8
    commands:
      - mvn clean test
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"

  - name: rebuild_cache
    image: curlimages/curl
    user: root
    environment:
      WEBDAV_CACHE_ADDRESS:
        from_secret: webdav-cache-address
      WEBDAV_CACHE_USERNAME:
        from_secret: webdav-cache-username
      WEBDAV_CACHE_PASSWORD:
        from_secret: webdav-cache-password
    commands:
      - curl -X MKCOL --user "$${WEBDAV_CACHE_USERNAME}:$${WEBDAV_CACHE_PASSWORD}" $${WEBDAV_CACHE_ADDRESS}/${DRONE_REPO_NAME} || true
      - curl -X MKCOL --user "$${WEBDAV_CACHE_USERNAME}:$${WEBDAV_CACHE_PASSWORD}" $${WEBDAV_CACHE_ADDRESS}/${DRONE_REPO_NAME}/${DRONE_BRANCH} || true
      - echo .m2 .cache | tr ' ' '\n' | xargs -P5 -i /bin/sh -c 'tar -C {} -c . | curl -T - --user "$${WEBDAV_CACHE_USERNAME}:$${WEBDAV_CACHE_PASSWORD}" $${WEBDAV_CACHE_ADDRESS}/${DRONE_REPO_NAME}/${DRONE_BRANCH}/$$(echo {} | tr -d / ) || true'
---
kind: signature
hmac: 1faf3036447ef1c31955b26515d90f27f23d75035831cd1351fee10dc776b29b

...
